M48
; DRILL file KiCad 10.0.5 date 2026-08-09T17:04:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-09T17:04:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X63.4Y-89.52
X75.1Y-89.52
T2
X54.0Y-54.0
X54.0Y-91.0
X101.0Y-54.0
X101.0Y-91.0
M30
